############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

accept-terms-of-use: true

##############
# Connectivity
beacon-rpc-provider: beacon:4000
monitoring-host: 0.0.0.0

grpc-gateway-host: 0.0.0.0 # web-ui

#########
# Web-UI
web: true

#####################################
# Validator database, accounts & key management
datadir: /data/db
wallet-dir: /data/wallets
wallet-password-file: /data/passwords/wallet-password
suggested-fee-recipient: 0x41b4099b9f3AD682eCBCa7B0f1C96544aeD2b3c3
enable-builder: true

mainnet: true

###########
# Fun Stuff
graffiti: ""